### ISSUE TITLE
Classes - found problems

### ISSUE THREAD

**Issue by chrunda** [Educ-IO/educ-io.github.io#1]
Hello, I have 2 problems with the Classes app:
1. Overview/All classes perform loading of information but at the end of the process nothing happens, I just see the same page. After many attempts I have only 2 succesfull cases of informaton loading. I am using Mozzila Firefox, your web has pop-up windows allowed.
2. Export to MS Excel works but it is unusable. Information of any cell is presented in 1 row (I have to double click each cell to show it corectly), different types of information is presented in one cell (better would be to separate it to one cell for one type of information within one column), Teacher's and Student's names are replaced by "work" word sometimes and are mixed with "C" information (Classwork Assignments). If I export all courses of our school it takes me 1 hour to fix the table so it is presentable to others.

Application is very usefull, but it should work on first run. Excel output is crucial for many of us and you could work on it as we can better use the presented information.

**Comment by thiscouldbejd** [comment]
Hi,

Thanks for getting in touch and raising these problems!

Will deal with them in turn...

1/ Can you give me a few more details about your domain? E.g. firstly, do you know (roughly) how many classrooms you have - and are you logged on as the domain admin (e.g. so all classes are visible) or a regular teacher (just your classes)? I have tested it up to maybe 500 classrooms, but don't have a domain with more classes than that...so am working a little blind for those large domains. On the occasions when it does not load properly - can you open the developer tools in Firefox - and let me know if there are any errors logged in the web-console? I can then try to work out a better way to handle large sets of classrooms!

2/ Am actually working on an updated version at the moment - it will have a slightly improved spreadsheet output (getting rid of the bits that are not needed etc). It will also have the ability to output a proper cross-classroom gradesheet (for student grading / work analysis) and also the ability to save the whole loaded data analysis in Google Drive - meaning you can share the analysis with non-G-Suite Admins, which might make things easier for you. What sort of data are you looking to share ideally?

Thanks,

JD

**Comment by chrunda** [comment]
Hi,

To your questions:

1.       We have 96 courses within 28 classrooms. I am logged as G Suite domain superadministrator at your web page. Here you have screenshot of errors:

 



 

2.       I really don’t know, what data we will be sharing. We are new in G Suite, started week ago. I think I will send outputs and statistic to school director so he can manage the teachers. I am old-school Excel user, really don’t use shared Google drive documents, but I see the benefit. It is interesting, that if I export your data to Google Sheets, information is visible correctly. It means I don’t have to double-click single cells to expand them. But the rest of my notices for Excel is valid also for Sheets. If I may choose, what data to share, it would be following columns (added also suggestions for change):

 


ID

Don't need, ordinal number 1 to X would be enough


Calendar

Don't need


State

OK


Name

OK, rename to "Course name"


Fetched

Don't need


Section

OK, rename to "Course section"


Guardians

OK, switch with "Room" column, rename values: "true" to "Invited", "false" to "Not invited"


Room

OK, rename to "Course room", switch with "Guardians" column


Updated

OK, switch with "Created" column


Created

OK, switch with "Updated" column


Teachers

OK, separate output values to single columns, i.e.: "Name", "Classwork", "Announcements", put "Name" data to single rows (better filtering options)


Students

OK, separate output values to single columns, i.e.: "Name", "Classwork", "Announcements", put "Name"  data to single rows (better filtering options)


Code

OK, move in front of "Name" column


Usage

OK, separate output values to single columns, i.e.: "Students", "Teacher Announcements", "Student Announcements", "Classwork", "Topics", "Invited Students" (rename to "Rest of Invited Students", re-text also web object and its description, put next to new "Students" column) + maybe calculate new "Invited Students" column (= students + rest of invited students)


Engagement

OK, separate output values to single columns, i.e.: "Last 7 Days:", "Last 2 Weeks:", "Last 30 Days:", "Last 3 Months:"


Folder

Don't need


Owner

OK

                                                

If you need any further cooperation, don’t hesitate to contact me.

 

Sincerely

Jan Chramosta

**Comment by chrunda** [comment]
Sending errors once again, I've sent answer via Oulook and the picture didn't show here.
![Errors](https://user-images.githubusercontent.com/15208329/79137609-4a74ad80-7db3-11ea-8c4c-2ab4915a93b3.jpg)

**Comment by thiscouldbejd** [comment]
Hi Jan,

Great - thanks for the screenshots. That should be fixed now (the next time you reload the app, it should tell you that there is a new version to update to). The version with the fix is v0.0.4a-beta.

As for the export, I think this should be do-able, but will make this into a new 'report' feature - rather than use the existing 'export' button - as the export currently exports the visible view...and I think a transformed output would suit you best!

As mentioned previously - I have also added in the ability to download / save (to Google Drive) the analysed data - which means it can be shared with a non-G-Suite admin and they can load it in the app. This might make things a bit easier for you in terms of sharing with your school director. Other schools / colleges have been asking for a student-based view too (so they can see which students are engaged with the classes) - so have added this in as well.

If you can confirm that the main problem (not loading all classes) is now fixed for you in the latest version - then I will go ahead and close this issue, but carry on the conversation regarding the output to Excel via email if that is ok with you?

Thanks,

JD

**Comment by chrunda** [comment]
Hi,
3 of 3 loading attempts succesful. Good job.
No problem with email conversation about Excel.
Thanks

**Comment by thiscouldbejd** [comment]
Hi - great, will ping you an email about the Excel stuff then!

Speak soon,

JD
