### ISSUE TITLE
Acess problems

### ISSUE THREAD

**Issue by rhymer87** [Educ-IO/educ-io.github.io#2]
While using the app I was trying to fill in  Usage and Engagement columns. It requres the access to my account. While being a superadministrator in my G Suite for education domain I provided the access by turning on the Google class IP and adding the app to the whitelist. Unfortunately I still get an error.

Strangely, it works when I logg in as a pupil outside the organization's domain.
![nV1GT27CZrg](https://user-images.githubusercontent.com/64091340/79885530-bda7a080-83ff-11ea-887d-8e7009520b5f.jpg)

**Comment by thiscouldbejd** [comment]
Hi!

Thanks for raising this issue...I am sure we can work out what is going on.

Are you able to give me a bit more information about this part of your description:

"turning on the Google class IP and adding the app to the whitelist"

You shouldn't _need_ to add anything to a whitelist, unless you have an odd OAuth setup on your domain? It looks like the 'redirect_uri" in the request above is also not correct...which shouldn't happen! :)

Yours,

JD

**Comment by rhymer87** [comment]
![000](https://user-images.githubusercontent.com/64091340/80039983-bc5e9c80-8501-11ea-82a1-df7b01aa1922.jpg)
That is the screen of my whitelist in Security- API management.

I hope this would help.

**Comment by rhymer87** [comment]
Is there anything else I could provide to help with the solution of my issue?

**Comment by thiscouldbejd** [comment]
Hi - I will let you know if there is! I don't normally whitelist any OAuth Client IDs (as you have done) so I am going to test it out on my domain tomorrow morning to see if I can work out what is happening. Will let you know what I find out.

Yours,

JD

**Comment by thiscouldbejd** [comment]
Hi,

So - have had a look at what might be going on here...

I can't see anything that might be causing problems with that API trusted setting.

Can you confirm that you have Classroom API access turned on?

Google Admin Console -> Apps -> Additional Google Services -> Settings for Classroom -> Data Access

This should be ticked.

Thanks,

JD.

**Comment by rhymer87** [comment]
It is, though Classroom is not in additional google services - it is a part of G Suite for education

![image](https://user-images.githubusercontent.com/64091340/80211048-95a58080-863d-11ea-8880-138851a924f7.png)

**Comment by thiscouldbejd** [comment]
Ah yes, ok - sorry! Am testing on both a regular G-Suite domain and an education one :)

If you delete the trusted app from Security -> API Management, and then go through the sign-in procedure on the Classes app - can you tell me what happens?

Thanks,

JD

**Comment by rhymer87** [comment]
I still get the same Error 400: invalid_request
Account restricted

**Comment by thiscouldbejd** [comment]
Ok - completely understand! Am just trying to work out why you would be getting that error initially (e.g. forcing you to add it to the list of trusted apps). This isn't the _expected_ workflow for OAuth authorisation....so I think this is where we need to look at!

If you can you click on your name (in the top right hand side of the app), and then remove access to the app from your account (then sign out). This will completely de-register the app from having account access.

Then, if you sign in again - it should re-prompt you for access. Allow access to the relevant scopes, and then check this Admin Page: https://admin.google.com/ac/owl/list?tab=apps

You should be able to see the app on there, with *limited* access to 'Drive' and 'Other'. If you could confirm that is working ok.

Then you said that you were having a problem when trying to gather usage and engagement information? When you gather than information - it should then prompt for access to some new scopes (in particular the coursework, announcements, submissions and topic scopes. Can you try to allow those scopes and then let me know what you see if it fails.

The screenshot you posted originally doesn't seem to refer to this app, because the Client ID is different - as is the redirect! So am just trying to start from scratch to see what is going on :)

Thanks!

**Comment by rhymer87** [comment]
The problem remains. Everything worked as you described up to this line:

> You should be able to see the app on there, with limited access to 'Drive' and 'Other'. If you could confirm that is working ok.

However I still get an error while trying to gather usage and engagement information after I/m trying to allow those scopes.

**Comment by rhymer87** [comment]
![image](https://user-images.githubusercontent.com/64091340/80216442-b7efcc00-8646-11ea-923f-4056c296505a.png)

![image](https://user-images.githubusercontent.com/64091340/80216530-d6ee5e00-8646-11ea-8329-ebd5d9878dd2.png)

![image](https://user-images.githubusercontent.com/64091340/80216602-fab1a400-8646-11ea-9f29-9b918477da00.png)

![image](https://user-images.githubusercontent.com/64091340/80216646-0e5d0a80-8647-11ea-833f-9f54dc4505e4.png)

**Comment by thiscouldbejd** [comment]
Ok - thanks for testing. Those screenshots are really useful. I think the critical part of the error message we are seeing is "Account Restricted" - let me double check what could lead to that and get straight back to you! :)

**Comment by thiscouldbejd** [comment]
Hi - so, there isn't much documentation from Google about what the 'account_restricted' error actually means - and this is the first time I have seen it.

Quick question - do you have 'Advanced Protection' turned on for your admin account? (https://landing.google.com/advancedprotection/)

Thanks,

JD

**Comment by thiscouldbejd** [comment]
And finally (sorry this is taking so long), can you try re-adding the Classes OAuth Client ID to your trusted apps here:

https://admin.google.com/AdminHome?hl=en_GB#Oauth2ScopeManagement:subtab=trusted

The Client ID you should be adding is:

1015378489975-gsku4efgos0rgiooo579jfvku4771gad.apps.googleusercontent.com

Thanks.

**Comment by rhymer87** [comment]
> And finally (sorry this is taking so long), can you try re-adding the Classes OAuth Client ID to your trusted apps here:

I've just done it - the error is still there.

I'm not sure how to check it, but it doesn't seem that 'Advanced Protection' is on. I'm not sure though because I don't know where to look for the switcher.

**Comment by thiscouldbejd** [comment]
Hi - so, Advanced Protection is a setting in the Admin Console under users, select your admin user, then look at security. It should then say whether it is turned on or off for that account.

I have found a couple of posts referring to issues with 'restricted accounts' and the Topics OAuth scope. No-one seems to know where the restriction is coming from, and where (if anywhere) it can be turned off in Google Admin!

To confirm it is just this scope, are you able to test in the Google Developer site? It is quite straightforward....you just need the ID of one of your classrooms (you can get this from the overview screenshot in Classes that you posted above. If you expand the column before 'Name' on the left hand side, it should show the ID. Each classroom has a numerical ID (about 11 digits long). Grab this, then head over to:

https://developers.google.com/classroom/reference/rest/v1/courses.topics/list

Click 'Try It' on the right hand side, and enter in the Classroom / Course ID. Then click Execute. If you get the same error, we know it is definitely a Google restriction thing. If that is the case, could you also test:

https://developers.google.com/classroom/reference/rest/v1/courses.courseWork/list

And:

https://developers.google.com/classroom/reference/rest/v1/courses.announcements/list

If it is _just_ the Topics part that is causing the problem, then I can tweak the code to allow you to turn that off...and still get everything else.

I suspect you may have to raise the query with Google if we can't find the restriction setting in the Admin console...but we shall see!

Yours,

JD

**Comment by rhymer87** [comment]
Everything is exactly as you've expected!
The first link returns the error, but two remaining links work fine.

**Comment by thiscouldbejd** [comment]
Ok - that is cool. At least it narrows down the problem. I have no idea why the Topics should be considered 'sensitive' on your domain! However, to calculate usage and engagement - the topic information is useful but not essential. I will therefore make some code adjustments to allow you to exclude the OAuth topic request and carry on with the other two. That should make it fairly functional for the time being.

Not 100% sure when I will push the next update live (will include it in that). Maybe tomorrow if everything goes smoothly. I will update this issue when it goes live, to let you know you can test it.

Hope that is ok. Will also continue to see if I can find any info on what makes the account / domain 'restricted' in this way.

Yours,

JD

**Comment by rhymer87** [comment]
Thanks a lot! Good luck!

**Comment by thiscouldbejd** [comment]
Hi!

Pushed an updated version (Classes v0.0.4h-beta) live last night which allows you to cancel the Topics OAuth Request and it carry on working (just without pulling topics for Classwork in).

You might need to refresh a couple of times to get the new version (as it is Service Worker controlled) - but you should get a 'Update Available' banner to let you know that a new version is there.

When prompted for a set of permissions you can un-tick Topics, or just cancel out of the dialog if it is the only permission requested. Currently - it repeatedly prompts for the permission (each time you do something that wants that permission). I am adjusting this so it will remember your choice (per-session) and stop bugging you!

Let me know if this works ok for you - will continue to try and debug where this account restriction _actually_ comes from, so hopefully we can solve the problem properly!

Yours,

JD

**Comment by rhymer87** [comment]
It works perfectly! Thanks a lot!

![image](https://user-images.githubusercontent.com/64091340/80428552-c9f59700-88f2-11ea-972e-00d34b0e1e56.png)

**Comment by thiscouldbejd** [comment]
Great - very happy to hear that! There is also a 'limited' option under the 'Usage' button which might be easier for you too. Am currently working on making a few improvements and there will be another updated version this week.

Will close off this ticket, but I will re-open and post here if/when I find a solution to the OAuth issue in Google Admin for you! Feel free to re-open / open a new one if you need anything else :)

Yours,

JD
